spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sz_ai_hall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Admin123
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  mvc:
      static-path-pattern: /**
  resources:
      static-locations: classpath:templates/,file:/Users/luomingxing/tmp/
  servlet:
      multipart:
        enabled: true
        location: /Users/luomingxing/tmp
        file-size-threshold: 5MB
        max-file-size: 20MB
  mqtt:
    username:
    password:
    url: tcp://v2network.cn:1883
    completionTimeout: 3000
    default:
      topic: zungen
    client:
      id: zungen


logging:
  level:
    root: info
    com.mp.zungen: debug